const String ALBUM_LISTING_SCAFFOLD = "ALBUM_LISTING_SCAFOLD_KEY";



const String ALBUM_PHOTOS_LISTING_LISTVIEW_PROVIDER = "ALBUM_LISTING_LISTVIEW_PROVIDER";
const String ALBUM_LISTING_LISTVIEW_PROVIDER = "ALBUM_LISTING_LISTVIEW_PROVIDER";
const String ALBUM_LISTING_PROVIDER = "ALBUM_LISTING_PROVIDER";
